### PR TITLE
fix: setMockMethodCallHandler was removed from MethodChannel after up…

### PR DESCRIPTION
**Pull request by tshemeng**
fix setMockMethodCallHandler was removed from MethodChannel after upgrading flutter to v2.5.2

### CODE REVIEW

**Comment by tshemeng** [comment]
fix #1

**Comment by Hypatech** [comment]
Any chance of this being merged? Need it for a project

**Comment by lsegal** [comment]
Merged! Didn't realize this was used :)

**Comment by Hypatech** [comment]
Thank you!!!!!!!!!!!!!!!!!!!! 
🥺🥺🥺

**Pull request merged**
